name: messages_pro
description: An iMessage-like SMS app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  url_launcher: ^6.2.1
  
  flutter_sms_inbox: ^1.0.3
  flutter_contacts: ^1.1.7+1
  
  image_picker: ^1.0.7
  record: ^4.4.4 # نسخه 4 پایدارترین است
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  # vibration حذف شد (از HapticFeedback استفاده میکنیم)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
