name: messages_pro
description: An iMessage-like SMS app for Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_sms_inbox: ^1.0.3
  flutter_contacts: ^1.1.7+1
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.1
  flutter_local_notifications: ^17.0.0
  provider: ^6.1.1
  # پکیج‌های جدید برای کار کردن واقعی دکمه‌ها
  image_picker: ^1.0.7 # برای دوربین و گالری
  record: ^5.1.0 # برای ضبط صدا
  path_provider: ^2.1.2 # برای ذخیره فایل صدا
  audioplayers: ^6.0.0 # برای پخش صدا (اختیاری ولی خوبه باشه)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
