name: messages_pro
description: An iMessage-like SMS app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  url_launcher: ^6.2.1
  
  flutter_sms_inbox: ^1.0.3
  flutter_contacts: ^1.1.7+1
  
  image_picker: ^1.0.7
  record: ^5.2.0 # نسخه جدید برای حل مشکل اندروید
  audioplayers: ^6.0.0
  path_provider: ^2.1.2
  vibration: ^1.8.4

# بخش مهم: اجبار کردن نسخه‌های هماهنگ برای جلوگیری از ارور لینوکس
dependency_overrides:
  record_linux: ^1.2.1
  record_platform_interface: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
